version: "3.7"
services:
  psql:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${PSQL_PASS}
    ports:
      - "5432:5432"

  api:
    build: 
      context: ./
      dockerfile: Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=iotd.settings
      - RDS_DB_NAME=postgres
      - RDS_USERNAME=postgres
      - RDS_PASSWORD=${PSQL_PASS}
      - RDS_HOSTNAME=psql
      - RDS_PORT=5432
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
    ports:
      - "8000:8000"
    expose:
      - "8000"
    links:
      - psql