name: stsg-container-app-actions
on:
  push:
    branches:
      - master
jobs:
  UploadDocker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}      
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: docker
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/testing2:latest
  
  deployTerraform:
    env:
      environment: qa
    needs: UploadDocker
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-west-2
      
      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.7

      - name: Terraform Init
        run: terraform init --upgrade

      - name: Terraform Select Workspace ## Way to automatize workspace name by an environment variable
        run: terraform workspace select $environment || terraform workspace new $environment

      - name: Terraform Plan
        id: tfplan
        run: terraform plan -out=tfplan -detailed-exitcode -var="docker_image=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/testing2:latest" --var-file $environment.tfvars

        ### A manual approve and notify stage is recommended

      - name: Terraform Apply
        run: terraform apply --auto-approve -input=false tfplan