name: stsg-container-app-actions
on:
  push:
    branches:
      - master
jobs:
  UploadDocker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}      
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: docker
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/testing2:latest
